# Generated by Django 5.0.7 on 2024-08-02 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_course_tag_alter_user_options_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='imageblock',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='questionblock',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name': 'Текстовый блок', 'verbose_name_plural': 'Текстовые блоки'},
        ),
        migrations.AlterModelOptions(
            name='videoblock',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.questionblock', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_blocks', to='api.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for', to='api.answer', verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_blocks', to='api.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='questionblock',
            name='question_text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='api.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_blocks', to='api.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Файл видео'),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео'),
        ),
    ]
