# Generated by Django 5.0.7 on 2024-08-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_answer_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionblock',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='imageblock',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questionblock',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='videoblock',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.JSONField(default=dict, verbose_name='Контент урока'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ImageBlock',
        ),
        migrations.DeleteModel(
            name='QuestionBlock',
        ),
        migrations.DeleteModel(
            name='TextBlock',
        ),
        migrations.DeleteModel(
            name='VideoBlock',
        ),
    ]
