# Generated by Django 5.0.7 on 2024-08-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_questionblock_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
