# Generated by Django 5.0.7 on 2024-08-03 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lesson_avatar_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_courses', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
