# Generated by Django 5.0.7 on 2024-08-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed',
        ),
    ]
